name = "aoc"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-17"

[vars]
WORKERS_RS_VERSION = "0.0.14"

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
