[workspace]
members = [ "crates/*" ]
exclude = [ "crates/painter", "crates/fuzzing-afl" ]

[workspace.package]
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
edition = "2021"
homepage = "https://github.com/fornwall/advent-of-code"
license = "MIT"
repository = "https://github.com/fornwall/advent-of-code"
rust-version = "1.65"
version = "2019.12.472"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
