[workspace]
members = [ "crates/*" ]
exclude = [ "crates/painter", "crates/fuzzing-afl" ]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
