[build]
  publish = "crates/wasm/site"
  functions = "crates/wasm/functions/"
  command = "make netlify"

[[redirects]]
  from = "/solve/*"
  to = "/.netlify/functions/solve"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
