[package]
name = "advent-of-code-afl-fuzzing"
version = "2019.12.128"
keywords = ["advent-of-code", "rust", "afl", "fuzzing"]
categories = ["algorithms", "rust-patterns"]
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code"
description = "Fuzzing of solutions to Advent of Code written in Rust"
license = "MIT"
edition = "2018"

[dependencies]
advent-of-code = { path = "../core" }
afl = "*"

