[package]
name = "advent-of-code"
version = "2019.12.52"
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code"
license = "MIT"
description = "Solutions to Advent of Code written in Rust"
edition = "2018"

[lib]
name = "advent_of_code"

[dependencies]
bytecount = "0.*"
mod_exp = "1.*"
