[package]
name = "advent_of_code_rs"
version = "2019.12.36"
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code-2019-rs"
license = "MIT"
description = "Solutions to Advent of Code 2019 written in Rust"
edition = "2018"

[dependencies]
bytecount = "0.*"
mod_exp = "1.*"
