app = "advent-grpc"

[build]
  image = "fredrikfornwall/advent-of-code-grpc-server:2019.12.402"

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = "443"
