[package]
name = "advent-of-code-wasm"
version = "2019.12.150"
keywords = ["advent-of-code", "wasm", "webassembly", "node"]
categories = ["algorithms", "rust-patterns", "wasm"]
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code"
license = "MIT"
description = "Solutions to Advent of Code written in Rust"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
visualization = [ "advent-of-code/visualization" ]

[dependencies]
advent-of-code = { path = "../core" }
wasm-bindgen = "*"
wasm-bindgen-test = "*"
js-sys = "*"

[package.metadata.wasm-pack.profile.release]
# https://github.com/rustwasm/wasm-pack/issues/886
# is fixed with ""--enable-mutable-globals".
# But without "--no-validation" the build using nightly for the
# visualisation fails with "Fatal: module features do not match specified features"
wasm-opt = ["-O4", "--no-validation"]
