[package]
name = "advent-of-code-wasm"
version = "2019.12.213"
keywords = ["advent-of-code", "wasm", "webassembly", "node"]
categories = ["algorithms", "rust-patterns", "wasm"]
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code"
license = "MIT"
description = "Solutions to Advent of Code written in Rust"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
visualization = [ "advent-of-code/visualization", "advent-of-code-painter" ]
console-panic-hook = [ "console_error_panic_hook" ]

[dependencies]
advent-of-code = { path = "../core" }
advent-of-code-painter = { path = "../painter", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
wasm-bindgen = "*"
js-sys = "*"

[package.metadata.wasm-pack.profile.release]
# https://github.com/rustwasm/wasm-pack/issues/886
# is fixed with ""--enable-mutable-globals".
# But without "--no-validation" the build using nightly for the
# visualisation fails with "Fatal: module features do not match specified features"
wasm-opt = ["-O3", "--no-validation"]
