[package]
name = "advent-of-code-wasm"
version = "2019.12.111"
keywords = ["advent-of-code", "wasm", "webassembly", "node"]
categories = ["algorithms", "rust-patterns", "wasm"]
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code"
license = "MIT"
description = "Solutions to Advent of Code written in Rust"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
advent-of-code = { path = "../core" }
wasm-bindgen = "*"
wasm-bindgen-test = "*"
js-sys = "*"

[package.metadata.wasm-pack.profile.release]
# https://github.com/rustwasm/wasm-pack/issues/886
wasm-opt = ["-Oz", "--enable-mutable-globals"]
