name: Benchmark

on: push

jobs:
  benchmark-current:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - name: Install critcmp
      run: cargo install critcmp
    - name: Run benchmark on current commit
      run: |
        cd crates/core
        cargo bench -- --save-baseline new-baseline
        critcmp --export new-baseline > new-baseline.json
    - name: Upload benchmark on current commit
      uses: actions/upload-artifact@v2
      with:
        name: new-benchmark
        path: crates/core/new-baseline.json

  benchmark-previous:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: hecrj/setup-rust-action@v1
    - name: Install critcmp
      run: cargo install critcmp
    - name: Checkout previous commit
      run: git checkout HEAD~1
    - name: Run benchmark on previous commit
      run: |
        cd crates/core
        cargo bench -- --save-baseline old-baseline
        critcmp --export old-baseline > old-baseline.json
    - name: Upload benchmark on previous commit
      uses: actions/upload-artifact@v2
      with:
        name: old-benchmark
        path: crates/core/old-baseline.json

  compare-benchmarks:
    needs: [benchmark-current, benchmark-previous]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download benchmarks
      uses: actions/download-artifact@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: hecrj/setup-rust-action@v1
    - name: Install critcmp
      run: cargo install critcmp
    - name: Compare benchmarks on current and previous commit
      run: |
        critcmp old-benchmark/old-baseline.json new-benchmark/new-baseline.json > benchcmp.txt
        cat benchcmp.txt
    - name: Format commit comment
      id: get-comment-body
      run: |
        body=$(./.github/workflows/benchcmp-to-diff.py benchcmp.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}" 
        echo ::set-output name=body::$body
    - name: Post commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: ${{ steps.get-comment-body.outputs.body }}
    - run: ls -lha .github/workflows/

