name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5 setuptools_rust==0.11.3

      - name: Build wheels
        working-directory: crates/python/
        run: |
          export CIBW_BEFORE_BUILD='pip install setuptools-rust && curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh'
          export CIBW_SKIP='cp27-* cp34-*'
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: .crates/python/wheelhouse/*.whl
