name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v2

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly-2020-11-21

    - name: Generate code coverage
      # What about -all-features and --workspace?
      run: cargo +nightly-2020-11-21 tarpaulin --verbose --timeout 120 --out Xml
      working-directory: crates/core

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        directory: crates/core

