name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v2

    - name: Generate code coverage
      run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
      working-directory: crates/core

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        directory: crates/core

