name: Build

on:
  push:
    branches: [ master ]

jobs:

  build-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stable Docker image
      env:
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        docker login -u fredrikfornwall -p $DOCKER_ACCESS_TOKEN
        make publish-docker

