name: Fuzz with AFL

on: push

jobs:

  check-seed:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: Check seed
      run: cd crates/fuzzing-afl && ./check-seed.sh
      continue-on-error: true

  fuzz:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: Install current LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Fuzz with AFL
      run: LLVM_CONFIG=llvm-config-11 make fuzz-afl
      continue-on-error: true
