name: Fuzz with AFL

on: push

jobs:

  check-seed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - name: Check seed
      run: cd crates/fuzzing-afl && timeout 900s ./check-seed.sh
      continue-on-error: true

  fuzz:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - name: Install current LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Fuzz with AFL
      run: LLVM_CONFIG=llvm-config-11 AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 make fuzz-afl
    - name: List crashes found by fuzzing
      run: ls -lha ./crates/fuzzing-afl/target/crashes-to-upload/
    - name: Upload crashes found by fuzzing
      uses: actions/upload-artifact@v2
      with:
        path: ./crates/fuzzing-afl/target/crashes-to-upload/
        name: fuzzing-crashes-afl
