name: Bump version

on:
  push:
    branches: [ master ]

jobs:

  build-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install bump2version
      run: pip install bump2version
    - name: Setup git for commit
      run: |
        git config --global user.name 'Bump version workflow'
        git config --global user.email 'bumpversion@users.noreply.github.com'
    - name: Run bump2version
      run: bump2version --commit patch
    - name: Push changes to git
      run: git push
